USE crms_DB
GO

DROP PROCEDURE IF EXISTS add_user
DROP PROCEDURE IF EXISTS get_users
DROP PROCEDURE IF EXISTS get_single_users
DROP PROCEDURE IF EXISTS get_user_by_id
DROP PROCEDURE IF EXISTS get_employees
DROP PROCEDURE IF EXISTS update_user_det
DROP PROCEDURE IF EXISTS add_customer
DROP PROCEDURE IF EXISTS get_customers
DROP PROCEDURE IF EXISTS get_single_customer
DROP PROCEDURE IF EXISTS update_customer
DROP PROCEDURE IF EXISTS add_sale
DROP PROCEDURE IF EXISTS update_sale_state
DROP PROCEDURE IF EXISTS get_all_sales_with_products
DROP PROCEDURE IF EXISTS get_sale_details
DROP PROCEDURE IF EXISTS add_notification
DROP PROCEDURE IF EXISTS get_notitications
DROP PROCEDURE IF EXISTS add_category_staff
DROP PROCEDURE IF EXISTS add_category_admin
DROP PROCEDURE IF EXISTS update_category
DROP PROCEDURE IF EXISTS delete_category
DROP PROCEDURE IF EXISTS get_categories
DROP PROCEDURE IF EXISTS get_category_by_id
DROP PROCEDURE IF EXISTS add_product_staff
DROP PROCEDURE IF EXISTS add_product_admin
DROP PROCEDURE IF EXISTS delete_product
DROP PROCEDURE IF EXISTS update_product
DROP PROCEDURE IF EXISTS get_products
DROP PROCEDURE IF EXISTS get_product_by_id
DROP PROCEDURE IF EXISTS get_count_all
DROP PROCEDURE IF EXISTS get_top_customers
