# login to the system
###
POST  http://localhost:4000/users/login
Content-Type: application/json


{
    "email":"mungaijohn@gmail.com",
    "password":"ad472c52"

}

###
GET   http://localhost:4000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VhbGxvQGdtYWlsLmNvbSIsImlhdCI6MTY3OTkxODcyNSwiZXhwIjoxNjc5OTQwMzI1fQ.NV45iwD_RbcczhCKeAP780vX82WsVqaa6t8hXHIpV2M


###
POST http://localhost:4000/products/category/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11bmdhaWpvaG5AZ21haWwuY29tIiwiaWF0IjoxNjgwMDIyNTU5LCJleHAiOjE2ODAxMDg5NTl9.3Oq7F_Dq9dGeczZI9nev60ovROgOGPnShIEkcUOnZCM

# {   "role":"staff",
#     "categoryName":"Home made burns",
#     "description":"very healthy food",
#     "addedBy":105
# }

# {   "role":"admin",
#     "categoryName":" Women Clothes",
#     "description":"the best attires",
#     "addedBy":105
# }

# {   "role":"staff",
#     "categoryName":"Snezkers",
#     "description":"the best feet attires",
#     "addedBy":105
# }

{   "role":"staff",
    "categoryName":"fanimal fadrinks",
    "description":"the best mouth attires",
    "addedBy":105
}


#get all categories
###
GET http://localhost:4000/products/category/all-categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11bmdhaWpvaG5AZ21haWwuY29tIiwiaWF0IjoxNjgwMDIyNTU5LCJleHAiOjE2ODAxMDg5NTl9.3Oq7F_Dq9dGeczZI9nev60ovROgOGPnShIEkcUOnZCM



# get single category
###
GET http://localhost:4000/products/category/single/A477A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VhbGxvQGdtYWlsLmNvbSIsImlhdCI6MTY3OTkxODcyNSwiZXhwIjoxNjc5OTQwMzI1fQ.NV45iwD_RbcczhCKeAP780vX82WsVqaa6t8hXHIpV2M




# update category
###
PATCH  http://localhost:4000/products/category/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11dGhvbmlqYW5lQGV4YW1wbGUuY29tIiwiaWF0IjoxNjc5OTgwMTI5LCJleHAiOjE2ODAwMDE3Mjl9.Md2Av5JPrRO3pts2QAE7FP2R2FIrcIMJV5yvDLvdoq8

{
    "catId":"5F82D8",
    "categoryName":"Electronics",
    "description":"very healthy food biting",
    "updatedBy":105
}

#Delete category
###
DELETE  http://localhost:4000/products/category/delete/318E46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODk0NTgxLCJleHAiOjE2Nzk5MTYxODF9.-OWNaxIE7hrW1tRAWOhmZpjxHIIRHskjlRkD9nnFpyM

//PRODUCTS
# add prod
###
POST http://localhost:4000/products/add/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11bmdhaWpvaG5AZ21haWwuY29tIiwiaWF0IjoxNjgwMDIyNTU5LCJleHAiOjE2ODAxMDg5NTl9.3Oq7F_Dq9dGeczZI9nev60ovROgOGPnShIEkcUOnZCM

{
    "role":"staff",
    "productName":"Dominiz Dominoz",
    "description":"Perfect food ",
    "addedBy":107,
    "price":3,
    "quantity":100,
    "categoryId":"70DEAE",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11bmdhaWpvaG5AZ21haWwuY29tIiwiaWF0IjoxNjgwMDIyNTU5LCJleHAiOjE2ODAxMDg5NTl9.3Oq7F_Dq9dGeczZI9nev60ovROgOGPnShIEkcUOnZCM"
}


# {   "role":"admin",
#     "productName":"more Ringoz",
#     "description":"very healthy food for food",
#     "addedBy":105,
#     "price":5,
#     "quantity":120,
#     "categoryId":"70DEAE"
# }

# {   "role":"admin",
#     "productName":"Huawei drier",
#     "description":"spin and dry",
#     "addedBy":107,
#     "price":5,
#     "quantity":120,
#     "categoryId":"70DEAE"
# }


# edit prod
###
PATCH  http://localhost:4000/products/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODk0NTgxLCJleHAiOjE2Nzk5MTYxODF9.-OWNaxIE7hrW1tRAWOhmZpjxHIIRHskjlRkD9nnFpyM

{
    "id":"CAEAE7",
    "productName":"Huawei drier motor motor",
    "description":"spin and dry and clothe and go",
    "updatedBy":105,
    "price":10,
    "quantity":150,
    "approved":1
}

# all products
###
GET  http://localhost:4000/products/all
Content-Type: application/json
Authorization: Bearer 5F82D8

# single product
###
GET http://localhost:4000/products/single/CAEAE7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODk0NTgxLCJleHAiOjE2Nzk5MTYxODF9.-OWNaxIE7hrW1tRAWOhmZpjxHIIRHskjlRkD9nnFpyM


# delete a product
###
DELETE  http://localhost:4000/products/delete/CAEAE7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODk0NTgxLCJleHAiOjE2Nzk5MTYxODF9.-OWNaxIE7hrW1tRAWOhmZpjxHIIRHskjlRkD9nnFpyM