# background services
###
GET http://localhost:4000/notifications/


# all users
###
GET    http://localhost:4000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11dGhvbmlqYW5lQGV4YW1wbGUuY29tIiwiaWF0IjoxNjc5OTgwMTI5LCJleHAiOjE2ODAwMDE3Mjl9.Md2Av5JPrRO3pts2QAE7FP2R2FIrcIMJV5yvDLvdoq8

# add users
###
POST   http://localhost:4000/users/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2NDgwMiwiZXhwIjoxNjc5Nzg2NDAyfQ._DrbL5XKciAo2TZlf6Fnf6AFqitbuecYR5D50zkF-og

{
    "fullName":"mike Alloo",
    "phone":789856740,
    "email":"mikeallo@gmail.com",
    "gender":"male",
    "role":"staff",
    "password":"mypass1"
}

# {
#     "fullName":"Joanina  Mulwa",
#     "phone":712385687,
#     "email":"jmulwaa@gmail.com",
#     "gender":"female",
#     "role":"super admin",
#     "password":"mypass1"
# }

# login to the system
###
POST  http://localhost:4000/users/login
Content-Type: application/json


{
    "email":"muthonijane@example.com",
    "password":"mypass1"

}

#edit user details
###
PATCH  http://localhost:4000/users/update-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11dGhvbmlqYW5lQGV4YW1wbGUuY29tIiwiaWF0IjoxNjc5OTgwMTI5LCJleHAiOjE2ODAwMDE3Mjl9.Md2Av5JPrRO3pts2QAE7FP2R2FIrcIMJV5yvDLvdoq8

{
    "id":"105",
    "fullName":"Jane Muthoni",
    "email":"muthonijane@example.com",
    "phone":"25471285333"
}

# add customer
###
POST http://localhost:4000/users/add-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VhbGxvQGdtYWlsLmNvbSIsImlhdCI6MTY3OTkxODcyNSwiZXhwIjoxNjc5OTQwMzI1fQ.NV45iwD_RbcczhCKeAP780vX82WsVqaa6t8hXHIpV2M

{
    "fullName": "Mark Msee",
    "phone": "254706007400",
    "email": "mustafa@gmail.com",
    "gender":"male"
}

# {
#     "fullName": "Corey corey",
#     "phone": "2547060078678",
#     "email": "corey@gmail.com",
#     "gender":"male"
# }

# {
#     "fullName": "Corey mahn",
#     "phone": "254000600978",
#     "email": "kcore@gmail.com",
#     "gender":"male"
# }



# all customers
###
GET   http://localhost:4000/users/all-customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11dGhvbmlqYW5lQGV4YW1wbGUuY29tIiwiaWF0IjoxNjc5OTgwMTI5LCJleHAiOjE2ODAwMDE3Mjl9.Md2Av5JPrRO3pts2QAE7FP2R2FIrcIMJV5yvDLvdoq8


# single user
###
POST    http://localhost:4000/users/single-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pa2VhbGxvQGdtYWlsLmNvbSIsImlhdCI6MTY3OTkxODcyNSwiZXhwIjoxNjc5OTQwMzI1fQ.NV45iwD_RbcczhCKeAP780vX82WsVqaa6t8hXHIpV2M

{
    "phone":"25470607400"
}


# edit customer
###
PATCH  http://localhost:4000/users/edit-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im11dGhvbmlqYW5lQGV4YW1wbGUuY29tIiwiaWF0IjoxNjc5OTgwMTI5LCJleHAiOjE2ODAwMDE3Mjl9.Md2Av5JPrRO3pts2QAE7FP2R2FIrcIMJV5yvDLvdoq8

{
    "id":"113",
    "email":"jayagain@example.com",
    "phone":"2478909009"
}

# products sections
###
GET http://localhost:4000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2MDEwNywiZXhwIjoxNjc5NzYzNzA3fQ.t8yloS3Y7jB7uasPEqvK2x092gZq1HNdikOEc-i2CxA


###
GET http://localhost:4000/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2MDEwNywiZXhwIjoxNjc5NzYzNzA3fQ.t8yloS3Y7jB7uasPEqvK2x092gZq1HNdikOEc-i2CxA
