GET  http://localhost:5000/users/home

###
GET    http://localhost:4000/mien/


# background services
###
GET http://localhost:4000/notifications/


# all users
###
GET    http://localhost:4000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODk0NTgxLCJleHAiOjE2Nzk5MTYxODF9.-OWNaxIE7hrW1tRAWOhmZpjxHIIRHskjlRkD9nnFpyM

# add users
###
POST   http://localhost:4000/users/signup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2NDgwMiwiZXhwIjoxNjc5Nzg2NDAyfQ._DrbL5XKciAo2TZlf6Fnf6AFqitbuecYR5D50zkF-og

{
    "fullName":"jamaa Mwasiwa",
    "phone":706306800,
    "email":"jamaak@gmail.com",
    "gender":"male",
    "role":"staff",
    "password":"mypass1"
}

# {
#     "fullName":"Joanina  Mulwa",
#     "phone":712385687,
#     "email":"jmulwaa@gmail.com",
#     "gender":"female",
#     "role":"super admin",
#     "password":"mypass1"
# }

# login to the system
###
POST  http://localhost:4000/users/login
Content-Type: application/json


{
    "email":"jmulwaa@gmail.com",
    "password":"mypass1"

}

#edit user details
###
PATCH  http://localhost:4000/users/update-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YWFAZ21haWwuY29tIiwiaWF0IjoxNjc5ODU1MzIyLCJleHAiOjE2Nzk4NzY5MjJ9.H6XsfklR2nXPJ9LxRnmeegug70Qradw0T8Si6N0Wy2w

{
    "id":"2",
    "fullName":"Joanina Muthoni",
    "email":"muthoni@example.com",
    "phone":"25471285200"
}

# add customer
###
POST http://localhost:4000/users/add-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YUBnbWFpbC5jb20iLCJpYXQiOjE2Nzk4MTk4NDQsImV4cCI6MTY3OTg0MTQ0NH0.ceqmFLExuK0wPxQXpLML2GI4vVTFTjEHlKJaj9rRGeo

# {
#     "fullName": "Mark Msee",
#     "phone": "254706007400",
#     "email": "mustafa@gmail.com",
#     "gender":"male"
# }

# {
#     "fullName": "Corey corey",
#     "phone": "2547060078678",
#     "email": "corey@gmail.com",
#     "gender":"male"
# }

{
    "fullName": "Corey mahn",
    "phone": "254000600978",
    "email": "kcore@gmail.com",
    "gender":"male"
}



# all customers
###
GET   http://localhost:4000/users/all-customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2NDgwMiwiZXhwIjoxNjc5Nzg2NDAyfQ._DrbL5XKciAo2TZlf6Fnf6AFqitbuecYR5D50zkF-og


# single user
###
POST    http://localhost:4000/users/single-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YUBnbWFpbC5jb20iLCJpYXQiOjE2Nzk4MTk4NDQsImV4cCI6MTY3OTg0MTQ0NH0.ceqmFLExuK0wPxQXpLML2GI4vVTFTjEHlKJaj9rRGeo

{
    "phone":"2478909009"
}


# edit customer
###
PATCH  http://localhost:4000/users/edit-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptdWx3YUBnbWFpbC5jb20iLCJpYXQiOjE2Nzk4MTk4NDQsImV4cCI6MTY3OTg0MTQ0NH0.ceqmFLExuK0wPxQXpLML2GI4vVTFTjEHlKJaj9rRGeo

{
    "id":"1158",
    "email":"jayagain@example.com",
    "phone":"2478909009"
}

# products sections
###
GET http://localhost:4000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2MDEwNywiZXhwIjoxNjc5NzYzNzA3fQ.t8yloS3Y7jB7uasPEqvK2x092gZq1HNdikOEc-i2CxA


###
GET http://localhost:4000/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcmFrQGdtYWlsLmNvbSIsImlhdCI6MTY3OTc2MDEwNywiZXhwIjoxNjc5NzYzNzA3fQ.t8yloS3Y7jB7uasPEqvK2x092gZq1HNdikOEc-i2CxA
