GET  http://localhost:5000/users/home



# all users
###
GET    http://localhost:5000/users/


# add users
###
POST   http://localhost:5000/users/signup
Content-Type: application/json

{
    "fullName":"Mark Mwas",
    "phone":"254706306415",
    "email":"marks@gmail.com",
    "role":"staff",
    "password":"mypass1"
}

# login to the system
###
POST  http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"marks@gmail.com",
    "password":"mypass1"

}

# add customer
###
POST  http://localhost:5000/users/add-customer
Content-Type: application/json

{
    "fullName":"Mark Msee",
    "phone":"254706306400",
    "email":"marksmsee@gmail.com"
}


# all customers
###
GET   http://localhost:5000/users/all-customers


# single user
###
POST    http://localhost:5000/users/single-customer
Content-Type: application/json

{
    "phone":"254706306400"
}

